// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerApp;

#nullable disable

namespace ServerApp.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240309003259_InsertOsobaConstitionSP")]
    partial class InsertOsobaConstitionSP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServerApp.Models.Mesto", b =>
                {
                    b.Property<long>("M")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("m");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("M"));

                    b.Property<int>("BrojStanovnika")
                        .HasColumnType("int")
                        .HasColumnName("broj_stanovnika");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("naziv");

                    b.Property<string>("PttBroj")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ptt_broj");

                    b.HasKey("M");

                    b.ToTable("mesto");
                });

            modelBuilder.Entity("ServerApp.Models.Osoba", b =>
                {
                    b.Property<long>("O")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("o");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("O"));

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("broj_telefona");

                    b.Property<DateOnly>("DatumRodjenja")
                        .HasColumnType("date")
                        .HasColumnName("datum_rodjenja");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("nvarchar(33)")
                        .HasColumnName("ime");

                    b.Property<string>("Jmbg")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("jmbg");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("nvarchar(33)")
                        .HasColumnName("prezime");

                    b.Property<long>("RodnoMesto")
                        .HasColumnType("bigint")
                        .HasColumnName("rodno_mesto");

                    b.Property<int>("Starost")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("starost")
                        .HasComputedColumnSql("datediff(month,[datum_rodjenja,getdate()])");

                    b.HasKey("O");

                    b.HasIndex("Jmbg")
                        .IsUnique();

                    b.HasIndex("O")
                        .IsUnique();

                    b.HasIndex("RodnoMesto");

                    b.ToTable("osoba");
                });

            modelBuilder.Entity("ServerApp.Models.Prebivaliste", b =>
                {
                    b.Property<long>("O")
                        .HasColumnType("bigint")
                        .HasColumnName("o");

                    b.Property<long>("M")
                        .HasColumnType("bigint")
                        .HasColumnName("m");

                    b.HasKey("O", "M");

                    b.HasIndex("M");

                    b.ToTable("prebivaliste");
                });

            modelBuilder.Entity("ServerApp.Models.Osoba", b =>
                {
                    b.HasOne("ServerApp.Models.Mesto", null)
                        .WithMany()
                        .HasForeignKey("RodnoMesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ServerApp.Models.Prebivaliste", b =>
                {
                    b.HasOne("ServerApp.Models.Mesto", null)
                        .WithMany()
                        .HasForeignKey("M")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServerApp.Models.Osoba", null)
                        .WithMany()
                        .HasForeignKey("O")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
